#.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## XYZ Informations
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
#.title~

name: xyz_informations
version: 0.1.0
publish_to: none

## -----------------------------------------------------------------------------

environment:

  sdk: ^3.1.5

## -----------------------------------------------------------------------------

dependencies:

  http:
  shelf_router:
  xml:
  html:
  mime:
  archive:
  js:

  xyz_utils:
    git:
      url: https://github.com/robmllze/xyz_utils.git
  
  xyz_gen:
    git:
      url: https://github.com/robmllze/xyz_gen.git

## -----------------------------------------------------------------------------

dev_dependencies:

  build_runner: ^2.4.6
  build_web_compilers: ^4.0.7
  lints:
